apiVersion: v1
kind: PersistentVolume
metadata:
  name: gauntlt-pv
  labels:
    type: nfs
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  nfs:
    path:  /srv/nfs/roseaw         #local reference
    server: 10.48.10.140
  persistentVolumeReclaimPolicy: Retain
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gauntlt-pvc    
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  selector:
    matchLabels:
      type: nfs
---      
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gauntlt-deployment
  labels:
    app: gauntlt
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gauntlt
  template:
    metadata:
      labels:
        app: gauntlt
    spec:
      containers:
        - name: gauntlt
          image: cithit/gauntlt:latest
          ports:
            - containerPort: 80
          volumeMounts:
            - name: nfs-storage
              mountPath: /nfs       
      volumes:
        - name: nfs-storage
          persistentVolumeClaim:
            claimName: gauntlt-pvc    
---
apiVersion: v1
kind: Service
metadata:
  name: gauntlt-dev-service
spec:                                   
  ports:
  - protocol: TCP
    port: 80  
    targetPort: 80
  selector:
    app: gauntlt
